# Generated by Django 4.0.4 on 2022-04-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_cart_order_customer_cartproduct_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
