# Generated by Django 4.0.4 on 2022-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_curousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
